# EM_Plot plots the absolute latitudinal range of each ASV against occupancy in ontological groups (e.g. EMPO 3) 

library(ggplot2)
library(data.table)
library(gridExtra)
library(ggpubr)

## Read In Data ----------------------------------
# generated by script EM_Range.R

ASV_ranges <- readRDS("../data/processed/sample_range_correlation.rds")[[1]]

empo_1 <- readRDS("../data/processed/empo_ranges/empo_1_sample_range_correlation.rds")[[1]]

empo_2 <- readRDS("../data/processed/empo_ranges/empo_2_sample_range_correlation.rds")[[1]]

empo_3 <- readRDS("../data/processed/empo_ranges/empo_3_sample_range_correlation.rds")[[1]]

props <- fread("../data/processed/all_empo3_proportions.csv")

source("../src/get_colors.R")

## Plot proportions of EMPO 3 in EMP and Waimea ---------------

# proportions from raw counts
props <- props[Dataset %in% c("Waimea","EMP")]
props[ , sample_prop := sample_count/sum(sample_count), by = Dataset]
props[ , read_prop := read_sum/sum(read_sum), by = Dataset]

# plot
emp_colors <-get_waimea_colors(return_all = T, cat_type = "emp")
p1<- ggplot(props, aes(x = Dataset, y = sample_prop, fill = empo_3))+
  geom_bar(stat = "identity", position = "dodge")+
  labs(title = "Proportion EMPO 3 By Sample Count")+
  scale_fill_manual(values = emp_colors)+
  theme_minimal()

ggsave("../outputs/figures/prop_by_sample_count.png", width = 8, height = 5, plot = p1)

p2 <- ggplot(props, aes(x = Dataset, y = read_prop, fill = empo_3))+
  geom_bar(stat = "identity", position = "dodge")+
  labs(title = "Proportion EMPO 3 By Reads")+
  scale_fill_manual(values = emp_colors)+
  theme_minimal()
ggsave("../outputs/figures/prop_by_sequencing_depth.png", width = 8, height = 5, plot = p2)

## Calculate Linear Models-------------------------

# range_mod() gets all the components together for plotting range vs. sample type
range_mod <- function(range_dat) {
  # subset data based on minimum range and occupancy
  range_dat <- range_dat[range_coord > 0 & group_count > 1]
  
  # calculate linear model
  range_mod <-
    lm(log(range_coord + 1) ~ log(group_count), data = range_dat)
  
  # run anova
  range_anova <- summary(range_mod)
  
  # predict confidence intervals
  conf_int <-
    predict(range_mod, interval = "confidence", level = 0.95)
  
  out <- list(range_dat, conf_int, range_mod, range_anova)
  names(out) <- c("data", "conf_interval", "range_mod", "anova_sum")
  
  return(out)
  
}

# run on the sample types
empo_1_mod <- range_mod(empo_1)
empo_2_mod <- range_mod(empo_2)
empo_3_mod <- range_mod(empo_3)

sample_type_mod <- range_mod(ASV_ranges)

## Plot Distributions------------------------
hist1 <- ggplot(sample_type_mod$data)+
  geom_histogram(aes(x = group_count))+
  labs(x = "Number of Sample Types", title =  "Histogram: Number of Sample Types")

hist2 <- ggplot(sample_type_mod$data)+
  geom_histogram(aes(x = range_coord))+
  labs(x = "Range in Latitude", title ="Histogram: Number of Sample Types")


hist3 <- ggplot(sample_type_mod$data)+
  geom_histogram(aes(x = log(group_count +1 )))+
  labs(x = "Number of Sample Types", title =  "Histogram: Number of Sample Types")

hist4 <- ggplot(sample_type_mod$data)+
  geom_histogram(aes(x = log(range_coord+1)))+
  labs(x = "Range in Latitude", title ="Histogram: Number of Sample Types")
hist4

ggsave(hist1, "../outputs/figures/n_samples_hist.png")
ggsave(hist2, "../outputs/figures/range_lat_hist.png")
ggsave(hist3, "../outputs/figures/log_n_samples_hist.png")
ggsave(hist4, "../outputs/figures/log_range_lat_hist.png")


## Plot EMPO ASV Range Correlation------------------------
plot_range_cor <- function(plot_mod, description = NULL) {
  p <-
    ggplot(plot_mod$data,  aes(x = group_count, y = log(range_coord + 1))) +
    # density
    stat_bin_2d(aes(fill = log(..count..))) +
    scale_fill_viridis_c() +
    # scales and labels
    theme(panel.grid.minor = element_blank()) +
    scale_x_continuous(breaks = seq_len(max(plot_mod$data$group_count)),
                       expand = expansion(c(0, .01))) +
    labs(title = "Global Range vs. Distribution Across Sample Types ",
         caption = paste( 
           "P =", signif(plot_mod$anova_sum$coefficients[8], 3),"   ",
           "R^2 = ",signif(plot_mod$anova_sum$r.squared, 3)
         ),
         color = "Latitude Range",
         x = "Number of Sample Types",
         y = "Global Range in Latitude") +
    theme_classic() +
    geom_ribbon(
      aes(ymin = plot_mod$conf_interval[, 2], ymax = plot_mod$conf_interval[, 3]),
      color = "blue",  fill = "blue", alpha = 0.2
    )
  p
  # save plot
  ggsave( 
          filename = paste0("../outputs/figures/", description, "_range_correlation.png"),
          p, width = 10
  )
  
}

plot_range_cor(sample_type_mod, "sample_type")
plot_range_cor(empo_2_mod, "empo_2")
plot_range_cor(empo_3_mod, "empo_3")

